### PR TITLE
Upadate chokidar to latest version

### PR DESCRIPTION
**Pull request by janwiemers**
This pull request fixes a security vulnerability NODE-SECURITY-786 (https://nodesecurity.io/advisories/786)

The one thing killing me right now is that one test is `broken` with and without my changes. Can you weight in here?

```
When using forever-monitor an instance of Monitor with valid options setting hideEnv when spawning all-env-vars.js
    ✗ should hide the environment variables passed to the child
        » expected 1,
  	got	 0 (==) // macros.js:14
```

Thanks
Jan

### CODE REVIEW

**Comment by kibertoad** [comment]
@janwiemers Thanks! Will take a look.

**Comment by smhg** [comment]
LGTM!
On my machine (Linux) all tests run fine. At least on node <= 11.
There is another error in tests on node >= 12, but that has nothing to do with bumping `chokidar`.

@kibertoad you need some (minor) help maintaining this?

**Comment by kibertoad** [comment]
@smhg Unfortunately, at this point problem is not the lack of maintainers. Creator of this library does not trust anyone other than himself to publish new version of the library, and unfortunately he doesn't have any time for the project anymore, and that makes any changes done on the repository meaningless. His position is understandable, since forever is used for running huge amount of mission-critical production system, but this leaves no path forward for the project, unfortunately.
For all intents and purposes `forever` should be considered dead, and you are much better off migrating to anything else, such as `pm2` or `nodemon`.

**Comment by smhg** [comment]
@kibertoad that's a very reasonable and responsible approach in this scenario. Thank you both for thinking this through and taking the time to provide feedback!

Unrelated and only out of curiosity: why the recent (small) commits to both this and the forever repo?

**Comment by indexzero** [comment]
`forever` is not dead. If I've been difficult to reach please accept my apologies – unfortunately I cannot discuss why but one day soon I hope to share what has been taking up the bulk of my time the last few years. It's quite personal and prolonged. 

Until then thanks for trying to help here @kibertoad, but again, I assure you – this project is not dead.

**Comment by kibertoad** [comment]
@smhg So, latest update: we finally had a chat with @indexzero and he handled everything in a super classy way; now active support for `forever` has restarted, and I would be most happy to accept any and all help that you would be willing to offer; if after a while of contributing to `forever` you'll still feel comfortable to keep doing so (I must warn you, its codebase is not exactly for the faint of the heart, though 😅 ), you would be most welcome to join ranks of maintainers :)

**Comment by kibertoad** [comment]
@smhg Any chance you could take a look at https://github.com/foreversd/forever-monitor/issues/177?

**Comment by kibertoad** [comment]
Released in forever@2.0.0

**Pull request closed without merging**
