### PR TITLE
fix: Update ps-tree to 1.2.0

### PR DESCRIPTION
**Pull request by ffflorian**
This closes https://github.com/foreversd/forever-monitor/issues/163.

cc @kibertoad

### CODE REVIEW

**Comment by ffflorian** [comment]
@kibertoad thanks for the quick merge! When do you plan to release a new version?

**Comment by kibertoad** [comment]
I can cut one today :)

**Comment by ffflorian** [comment]
> I can cut one today :)

That would be great :)

**Comment by ffflorian** [comment]
Hey @kibertoad, what about that new version? :)

**Comment by kibertoad** [comment]
@ffflorian Sorry, got distracted before publishing it the last time. 3.0.1 is out now, thank you for the reminder!
Do you need new version of `forever` as well, or just `forever-monitor` is fine?

**Comment by ffflorian** [comment]
Thank you :)
I don't need a new version of `forever`.

**Pull request merged**
